system:
  env: 'dev'  # Change to "develop" to skip authentication for development mode
  addr: '127.0.0.1:8090'
  db-type: 'pgsql'
  oss-type: 'local'    # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

mysql:
  path: ''   # 链接地址
  port: ''   # 链接端口
  config: ''  # 其他配置 例如时区
  db-name: ''  # 数据库名称
  username: '' # 数据库用户名
  password: '' # 数据库密码
  charset: '' #字符集
  max-idle-conns: 10 # 连接池相关
  max-open-conns: 100 # 连接池相关
  log-mode: "" # 是控制台打印日志级别 "silent"、"error"、"warn"、"info" 不填默认info  填入silent可以关闭控制台日志
  log-zap: false # 日志是否用zap保存到本地

pgsql:
  Addr: '47.110.42.73'   # 链接地址
  port: 30232   # 链接端口
  config: ''  # 其他配置 例如时区
  db-name: 'test_pipline'  # 数据库名称
  username: 'postgres' # 数据库用户名
  password: 'Tu4fPn#3u%BI&iMezEsz' # 数据库密码
  max-idle-conns: 10 # 连接池相关
  max-open-conns: 100 # 连接池相关
  log-mode: "" # 是控制台打印日志级别 "silent"、"error"、"warn"、"info" 不填默认info  填入silent可以关闭控制台日志
  log-zap: false # 日志是否用zap保存到本地

redis:
  Addr: '47.110.42.73:30279'
  Password: 'NrJ*NVBa&OgE8B$y2Zgb'
  DB: 0
  IsOpenSentinel: false
  RedisSentinelIp: []
  ConnectTimeout: 300
  RedisPrefix: 'LightWeightPipline'

log:
  logPath: 'D:\\'
