// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"lightweightpipline/configs"
	"lightweightpipline/internal/biz/repo"
	repo2 "lightweightpipline/internal/data/repo"
	"lightweightpipline/third_party/redis_proxy"
)

// Injectors from wire.go:

// =========配置信息=========
func GetConfigure() (config.Configure, error) {
	configure, err := config.ProvideConfigure()
	if err != nil {
		return config.Configure{}, err
	}
	return configure, nil
}

// =========数据库上下文=========
// database
func GetDbContext() (*repo.DbContext, error) {
	configure, err := config.ProvideConfigure()
	if err != nil {
		return nil, err
	}
	dbContext, err := repo.ProvideDbContext(configure)
	if err != nil {
		return nil, err
	}
	return dbContext, nil
}

// redis
func NewRedis() (*redis_proxy.RedisClient, error) {
	configure, err := config.ProvideConfigure()
	if err != nil {
		return nil, err
	}
	redisClient, err := redis_proxy.NewRedisClient(configure)
	if err != nil {
		return nil, err
	}
	return redisClient, nil
}

// =========仓储层=========
func NewCommandRepo() (repo.ICommandRepo, error) {
	configure, err := config.ProvideConfigure()
	if err != nil {
		return nil, err
	}
	dbContext, err := repo.ProvideDbContext(configure)
	if err != nil {
		return nil, err
	}
	iCommandRepo, err := repo2.NewCommandRepo(dbContext)
	if err != nil {
		return nil, err
	}
	return iCommandRepo, nil
}

// wire.go:

var configureSet = wire.NewSet(config.ProvideConfigure)

var dbContextSet = wire.NewSet(configureSet, repo.ProvideDbContext)

var redisSet = wire.NewSet(configureSet, redis_proxy.NewRedisClient)

var commandRepoSet = wire.NewSet(dbContextSet, repo2.NewCommandRepo)
