// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"lightweightpipline/configs"
	"lightweightpipline/internal/biz/repo"
)

// Injectors from wire.go:

func GetConfigure() (config.Configure, error) {
	configure, err := config.ProvideConfigure()
	if err != nil {
		return config.Configure{}, err
	}
	return configure, nil
}

func GetDbContext() (*repo.DbContext, error) {
	configure, err := config.ProvideConfigure()
	if err != nil {
		return &repo.DbContext{}, err
	}
	dbContext, err := repo.ProvideDbContext(configure)
	if err != nil {
		return &repo.DbContext{}, err
	}
	return dbContext, nil
}

// wire.go:

var configureSet = wire.NewSet(config.ProvideConfigure)

var dbContextSet = wire.NewSet(configureSet, repo.ProvideDbContext)
